apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: mysql-phpipam
  name: deployment-mysql-phpipam
  namespace: ns-phpipam
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  selector:
    matchLabels:
      app: mysql-phpipam
  template:
    metadata:
      labels:
        app: mysql-phpipam
    spec:
      affinity: {}
      containers:
      - env:
        - name: MYSQL_ROOT_PASSWORD
          value: memora
        image: mysql:5.6
        imagePullPolicy: Always
        name: container-mysql-phpipam
        ports:
        - containerPort: 3306
          name: port-mysql
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /var/lib/mysql
          name: vol-ayziw
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - name: vol-ayziw
        persistentVolumeClaim:
          claimName: pvc-mysql-phpipam